FROM guangie88/rustfmt-clippy:1.27.0-nightly

WORKDIR /app
COPY ./Cargo.toml ./rustfmt.toml ./

RUN set -x \
    && cargo fetch -v

COPY ./src/ ./src/

RUN cargo clippy --all \
    && cargo test --all --no-run
